# generated by datamodel-codegen:
#   filename:  assurance-profile.schema.json

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Literal, Optional

from pydantic import BaseModel, ConfigDict, Field, RootModel


class FormalStatus(Enum):
    unformalized = 'unformalized'
    skeleton_only = 'skeleton_only'
    build_failed = 'build_failed'
    build_passed_no_proof = 'build_passed_no_proof'
    proof_complete = 'proof_complete'
    counterexample_found = 'counterexample_found'
    blocked = 'blocked'


class SupportStatus(Enum):
    none = 'none'
    literature_supported = 'literature_supported'
    experimentally_supported = 'experimentally_supported'
    simulation_supported = 'simulation_supported'
    test_supported = 'test_supported'
    mixed_supported = 'mixed_supported'
    challenged = 'challenged'
    refuted = 'refuted'


class IntentStatus(Enum):
    unreviewed = 'unreviewed'
    aligned = 'aligned'
    partially_aligned = 'partially_aligned'
    misaligned = 'misaligned'
    disputed = 'disputed'


class Gate(Enum):
    draft = 'draft'
    queued = 'queued'
    research_only = 'research_only'
    dev_guarded = 'dev_guarded'
    certified = 'certified'
    blocked = 'blocked'
    rejected = 'rejected'
    superseded = 'superseded'


class AllowedDownstreamEnum(Enum):
    research = 'research'
    dev = 'dev'
    release = 'release'
    monitoring = 'monitoring'


class Id(RootModel[str]):
    root: str = Field(..., pattern='^[A-Za-z0-9._:-]+$')


class System(Enum):
    isabelle_hol = 'isabelle_hol'
    lean = 'lean'
    coq = 'coq'
    agda = 'agda'
    other = 'other'


class TargetFormalArtifact(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    artifact_id: Id
    system: System
    session: str
    theory: str
    theorem: str


class TrustFrontier(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    global_axiom_dependency_count: int = Field(..., ge=0)
    locale_assumption_count: int = Field(..., ge=0)
    premise_assumption_count: int = Field(..., ge=0)
    oracle_dependency_count: int = Field(..., ge=0)
    unreviewed_import_count: int = Field(..., ge=0)
    transitive_dependency_count: int = Field(..., ge=0)
    reviewed_global_axiom_ids: list[Id]
    oracle_ids: list[Id]
    hotspot_artifact_ids: list[Id]
    notes: list[str]


class Conservativity(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    definitional_only: bool
    reviewed_global_axioms_required: bool
    compile_away_known: bool
    nondefinitional_hotspots: list[str]
    trusted_mechanisms: list[str]
    flagged_mechanisms: list[str]


class Obligations(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sorry_count: int = Field(..., ge=0)
    oops_count: int = Field(..., ge=0)
    open_goal_count: int = Field(..., ge=0)
    unresolved_bridge_count: int = Field(..., ge=0)
    missing_backtranslation_review_count: int = Field(..., ge=0)
    blocking_obligations: list[str]


class TriStatus(Enum):
    untested = 'untested'
    pass_ = 'pass'
    fail = 'fail'
    inconclusive = 'inconclusive'


class FragilityStatus(Enum):
    untested = 'untested'
    stable = 'stable'
    fragile = 'fragile'
    inconclusive = 'inconclusive'


class CountermodelProbe(Enum):
    untested = 'untested'
    no_countermodel_found = 'no_countermodel_found'
    countermodel_found = 'countermodel_found'
    inconclusive = 'inconclusive'


class ModelHealth(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    locale_satisfiability: TriStatus
    countermodel_probe: CountermodelProbe
    vacuity_check: TriStatus
    premise_sensitivity: FragilityStatus
    conclusion_perturbation: FragilityStatus
    notes: list[str]


class BacktranslationReview(Enum):
    unreviewed = 'unreviewed'
    pass_ = 'pass'
    fail = 'fail'
    needs_revision = 'needs_revision'


class IntentAlignment(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    independent_formalization_count: int = Field(..., ge=0)
    agreement_score: float = Field(..., ge=0.0, le=1.0)
    backtranslation_review: BacktranslationReview
    paraphrase_robustness_score: float = Field(..., ge=0.0, le=1.0)
    semantics_guard_violations: list[str]
    reviewer_notes: list[str]


class Coverage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    formalized_subclaim_count: int = Field(..., ge=0)
    residual_subclaim_count: int = Field(..., ge=0)
    dependency_coverage_score: float = Field(..., ge=0.0, le=1.0)
    evidence_link_coverage_score: float = Field(..., ge=0.0, le=1.0)
    required_claim_ids: list[Id]
    uncovered_claim_ids: list[Id]


class ReplayStatus(Enum):
    untested = 'untested'
    pass_ = 'pass'
    fail = 'fail'
    flaky = 'flaky'


class CrossToolReviewStatus(Enum):
    not_applicable = 'not_applicable'
    unreviewed = 'unreviewed'
    pass_ = 'pass'
    fail = 'fail'


class Robustness(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    linter_finding_count: int = Field(..., ge=0)
    replay_status: ReplayStatus
    rebuild_count: int = Field(..., ge=0)
    reproducibility_score: float = Field(..., ge=0.0, le=1.0)
    cross_tool_review_status: CrossToolReviewStatus
    notes: list[str]


class EvidenceCounts(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    experiment: int = Field(..., ge=0)
    literature: int = Field(..., ge=0)
    simulation: int = Field(..., ge=0)
    test_run: int = Field(..., ge=0)
    countermodel: int = Field(..., ge=0)
    manual_review: int = Field(..., ge=0)


class SupportProfile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    evidence_counts: EvidenceCounts
    strongest_positive_evidence_ids: list[Id]
    strongest_negative_evidence_ids: list[Id]
    bridge_notes: list[str]


class VectorScores(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    trust_base_integrity: int = Field(..., ge=0, le=100)
    intent_alignment: int = Field(..., ge=0, le=100)
    evidence_support: int = Field(..., ge=0, le=100)
    coverage: int = Field(..., ge=0, le=100)
    robustness: int = Field(..., ge=0, le=100)
    scheduler_score: Optional[int] = Field(None, ge=0, le=100)


class ProofClaim(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    score: int = Field(..., ge=0, le=100)
    scoreMethod: str
    scoreVersion: str
    scoreBreakdownRef: str


class Polarity(Enum):
    support = 'support'
    attack = 'attack'


class ProofClaimArgument(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    argumentId: Id
    label: str
    polarity: Polarity
    nodeConfidence: float = Field(..., ge=0.0, le=1.0)
    relationStrength: float = Field(..., ge=0.0, le=1.0)
    effectiveStrength: float = Field(..., ge=0.0, le=1.0)
    summary: str


class Dimension(Enum):
    trust_base_integrity = 'trust_base_integrity'
    intent_alignment = 'intent_alignment'
    evidence_support = 'evidence_support'
    coverage = 'coverage'
    robustness = 'robustness'


class ProofClaimDimension(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    dimension: Dimension
    baseScore: float = Field(..., ge=0.0, le=1.0)
    finalScore: float = Field(..., ge=0.0, le=1.0)
    supporters: list[ProofClaimArgument]
    attackers: list[ProofClaimArgument]


class ProofClaimBreakdown(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    scoreMethod: str
    scoreVersion: str
    aggregateBaseScore: float = Field(..., ge=0.0, le=1.0)
    aggregateFinalScore: float = Field(..., ge=0.0, le=1.0)
    dimensions: list[ProofClaimDimension]


class AssuranceProfile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: Literal['1.0.0']
    profile_id: Id
    project_id: Id
    created_at: datetime
    updated_at: datetime
    claim_id: Id
    claim_graph_ref: Optional[Id] = None
    assurance_graph_ref: Optional[Id] = None
    target_formal_artifact: TargetFormalArtifact
    formal_status: FormalStatus
    support_status: SupportStatus
    intent_status: IntentStatus
    gate: Gate
    decision_rationale: Optional[str] = None
    trust_frontier: TrustFrontier
    conservativity: Conservativity
    obligations: Obligations
    model_health: ModelHealth
    intent_alignment: IntentAlignment
    coverage: Coverage
    robustness: Robustness
    support_profile: SupportProfile
    vector_scores: VectorScores
    proofClaim: Optional[ProofClaim] = None
    proofClaimBreakdown: Optional[ProofClaimBreakdown] = None
    allowed_downstream: list[AllowedDownstreamEnum]
    required_actions: list[str]
    expires_at: Optional[datetime] = None
    supersedes_profile_id: Optional[Id] = None
