# generated by datamodel-codegen:
#   filename:  assurance-graph.schema.json

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Id(RootModel[str]):
    root: str = Field(..., pattern='^[A-Za-z0-9._:-]+$')


class Role(Enum):
    planner = 'planner'
    claim_graph_agent = 'claim_graph_agent'
    formalizer = 'formalizer'
    research = 'research'
    dev = 'dev'
    policy_engine = 'policy_engine'
    human_reviewer = 'human_reviewer'
    system = 'system'


class NodeStatus(Enum):
    active = 'active'
    provisional = 'provisional'
    approved = 'approved'
    failed = 'failed'
    obsolete = 'obsolete'
    rejected = 'rejected'


class ClaimNode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    node_id: Id
    node_type: Literal['claim']
    title: str
    summary: Optional[str] = None
    claim_ref: Id
    status: NodeStatus


class System(Enum):
    isabelle_hol = 'isabelle_hol'
    lean = 'lean'
    coq = 'coq'
    agda = 'agda'
    other = 'other'


class ArtifactKind(Enum):
    theorem = 'theorem'
    lemma = 'lemma'
    definition = 'definition'
    locale = 'locale'
    interpretation = 'interpretation'
    theory = 'theory'
    session_build = 'session_build'
    export_bundle = 'export_bundle'
    generated_code = 'generated_code'
    other = 'other'


class ProofStatus(Enum):
    draft = 'draft'
    built = 'built'
    proof_complete = 'proof_complete'
    build_failed = 'build_failed'
    obsolete = 'obsolete'


class FormalArtifactNode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    node_id: Id
    node_type: Literal['formal_artifact']
    title: str
    summary: Optional[str] = None
    system: System
    artifact_kind: ArtifactKind
    identifier: str
    session: Optional[str] = None
    theory: Optional[str] = None
    file_path: Optional[str] = None
    status: NodeStatus
    proof_status: ProofStatus


class EvidenceKind(Enum):
    experiment = 'experiment'
    literature = 'literature'
    simulation = 'simulation'
    benchmark = 'benchmark'
    test_run = 'test_run'
    countermodel = 'countermodel'
    static_analysis = 'static_analysis'
    runtime_observation = 'runtime_observation'
    manual_review = 'manual_review'
    bug_report = 'bug_report'
    other = 'other'


class ResultPolarity(Enum):
    supports = 'supports'
    challenges = 'challenges'
    refutes = 'refutes'
    mixed = 'mixed'
    neutral = 'neutral'


class EvidenceNode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    node_id: Id
    node_type: Literal['evidence']
    title: str
    summary: Optional[str] = None
    evidence_kind: EvidenceKind
    result_polarity: ResultPolarity
    artifact_refs: Optional[list[str]] = None
    confidence: Optional[float] = Field(None, ge=0.0, le=1.0)
    status: NodeStatus


class ScopeKind(Enum):
    premise = 'premise'
    locale = 'locale'
    global_axiom = 'global_axiom'
    environment_contract = 'environment_contract'


class AssumptionSetNode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    node_id: Id
    node_type: Literal['assumption_set']
    title: str
    summary: Optional[str] = None
    scope_kind: ScopeKind
    items: list[str] = Field(..., min_length=1)
    approved: bool
    status: NodeStatus


class ContractKind(Enum):
    implementation_contract = 'implementation_contract'
    research_task = 'research_task'
    test_obligation = 'test_obligation'
    runtime_guard = 'runtime_guard'
    release_gate = 'release_gate'
    review_obligation = 'review_obligation'
    other = 'other'


class ContractNode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    node_id: Id
    node_type: Literal['contract']
    title: str
    summary: Optional[str] = None
    contract_kind: ContractKind
    owner_role: Role
    status: NodeStatus
    acceptance_conditions: list[str]


class ReviewKind(Enum):
    backtranslation = 'backtranslation'
    intent_alignment = 'intent_alignment'
    formal_review = 'formal_review'
    evidence_review = 'evidence_review'
    safety_review = 'safety_review'
    release_review = 'release_review'
    other = 'other'


class Outcome(Enum):
    pass_ = 'pass'
    fail = 'fail'
    needs_revision = 'needs_revision'
    disputed = 'disputed'


class ReviewNode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    node_id: Id
    node_type: Literal['review']
    title: str
    summary: Optional[str] = None
    review_kind: ReviewKind
    reviewer_role: Role
    outcome: Outcome
    status: NodeStatus


class Node(
    RootModel[
        Union[
            ClaimNode,
            FormalArtifactNode,
            EvidenceNode,
            AssumptionSetNode,
            ContractNode,
            ReviewNode,
        ]
    ]
):
    root: Union[
        ClaimNode,
        FormalArtifactNode,
        EvidenceNode,
        AssumptionSetNode,
        ContractNode,
        ReviewNode,
    ]


class RelationType(Enum):
    formalizes = 'formalizes'
    backtranslates_to = 'backtranslates_to'
    depends_on = 'depends_on'
    scoped_by = 'scoped_by'
    supports = 'supports'
    challenges = 'challenges'
    refutes = 'refutes'
    reviews = 'reviews'
    derived_from = 'derived_from'
    implements = 'implements'
    tests = 'tests'
    gates = 'gates'
    supersedes = 'supersedes'
    generated_from = 'generated_from'
    equivalent_to = 'equivalent_to'


class Status(Enum):
    active = 'active'
    provisional = 'provisional'
    rejected = 'rejected'
    superseded = 'superseded'
    archived = 'archived'


class Edge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    edge_id: Id
    source_id: Id
    target_id: Id
    relation_type: RelationType
    status: Status
    rationale: Optional[str] = None
    strength: Optional[float] = Field(None, ge=0.0, le=1.0)


class AssuranceGraph(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: Literal['1.0.0']
    graph_id: Id
    project_id: Id
    created_at: datetime
    updated_at: datetime
    description: Optional[str] = None
    nodes: list[Node] = Field(..., min_length=1)
    edges: list[Edge]
