# generated by datamodel-codegen:
#   filename:  claim-graph.schema.json

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Literal, Optional

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Id(RootModel[str]):
    root: str = Field(..., pattern='^[A-Za-z0-9._:-]+$')


class Role(Enum):
    user = 'user'
    planner = 'planner'
    claim_graph_agent = 'claim_graph_agent'
    formalizer = 'formalizer'
    research = 'research'
    dev = 'dev'
    policy_engine = 'policy_engine'
    human_reviewer = 'human_reviewer'
    system = 'system'


class SourceType(Enum):
    user_message = 'user_message'
    planner_note = 'planner_note'
    research_note = 'research_note'
    dev_note = 'dev_note'
    document = 'document'
    issue = 'issue'
    meeting_note = 'meeting_note'
    external_source = 'external_source'
    other = 'other'


class SourceAnchor(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source_type: SourceType
    source_ref: str
    excerpt: Optional[str] = None
    span_start: Optional[int] = Field(None, ge=0)
    span_end: Optional[int] = Field(None, ge=0)


class Modality(Enum):
    universal = 'universal'
    existential = 'existential'
    high_probability = 'high_probability'
    average_case = 'average_case'
    worst_case = 'worst_case'
    interface_contract = 'interface_contract'
    empirical = 'empirical'
    design_intent = 'design_intent'
    optimization = 'optimization'
    other = 'other'


class Scope(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    domain: str
    modality: Modality
    included_conditions: list[str]
    excluded_conditions: list[str]


class SemanticsGuard(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    must_preserve: list[str]
    allowed_weakenings: list[str]
    forbidden_weakenings: list[str]
    forbidden_strengthenings: list[str]
    backtranslation_required: bool
    independent_formalizations_required: int = Field(..., ge=0, le=10)


class AllowedAssumptionCarrier(Enum):
    premise = 'premise'
    locale = 'locale'
    reviewed_global_axiom = 'reviewed_global_axiom'


class ClaimPolicy(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    allowed_assumption_carriers: list[AllowedAssumptionCarrier] = Field(
        ..., min_length=1
    )
    global_axiom_allowed: bool
    sorry_allowed_in_scratch: bool
    sorry_allowed_in_mainline: bool


class Provenance(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    created_by_role: Role
    source_anchors: list[SourceAnchor] = Field(..., min_length=1)
    last_reviewed_by_role: Optional[Role] = None
    review_notes: Optional[list[str]] = None


class ClaimClass(Enum):
    core_claim = 'core_claim'
    enabling_claim = 'enabling_claim'
    assumption = 'assumption'
    metric = 'metric'
    evaluator = 'evaluator'
    policy_variable = 'policy_variable'
    implementation_detail = 'implementation_detail'
    runtime_artifact = 'runtime_artifact'
    research_question = 'research_question'
    appendix = 'appendix'


class ClaimKind(Enum):
    theorem_candidate = 'theorem_candidate'
    definition_candidate = 'definition_candidate'
    hypothesis = 'hypothesis'
    invariant = 'invariant'
    interface_contract = 'interface_contract'
    optimization_goal = 'optimization_goal'
    empirical_generalization = 'empirical_generalization'
    evaluation_criterion = 'evaluation_criterion'
    design_principle = 'design_principle'
    safety_property = 'safety_property'
    liveness_property = 'liveness_property'
    other = 'other'


class Status(Enum):
    proposed = 'proposed'
    candidate = 'candidate'
    queued_for_formalization = 'queued_for_formalization'
    formalizing = 'formalizing'
    blocked = 'blocked'
    research_only = 'research_only'
    dev_only = 'dev_only'
    certified = 'certified'
    rejected = 'rejected'
    superseded = 'superseded'
    archived = 'archived'


class DownstreamKind(Enum):
    research_only = 'research_only'
    dev_only = 'dev_only'
    research_then_dev = 'research_then_dev'
    dev_then_research = 'dev_then_research'
    no_downstream = 'no_downstream'


class Claim(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    claim_id: Id
    title: str
    nl_statement: str
    normalized_statement: Optional[str] = None
    intent_gloss: Optional[str] = None
    claim_class: ClaimClass
    claim_kind: ClaimKind
    status: Status
    formalization_required: bool
    downstream_kind: DownstreamKind
    priority: Optional[int] = Field(None, ge=0, le=100)
    tags: Optional[list[str]] = None
    notes: Optional[list[str]] = None
    scope: Scope
    semantics_guard: SemanticsGuard
    policy: ClaimPolicy
    provenance: Provenance
    owner_role: Role
    reviewer_roles: list[Role]
    supersedes: Optional[list[Id]] = None


class RelationType(Enum):
    depends_on = 'depends_on'
    refines = 'refines'
    specializes = 'specializes'
    generalizes = 'generalizes'
    conflicts_with = 'conflicts_with'
    supersedes = 'supersedes'
    decomposes_into = 'decomposes_into'
    blocks = 'blocks'
    motivates = 'motivates'
    alternative_to = 'alternative_to'


class Status1(Enum):
    active = 'active'
    provisional = 'provisional'
    rejected = 'rejected'
    superseded = 'superseded'
    archived = 'archived'


class Relation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    relation_id: Id
    from_claim_id: Id
    to_claim_id: Id
    relation_type: RelationType
    status: Status1
    required_for_promotion: Optional[bool] = None
    rationale: Optional[str] = None


class DefaultAssumptionCarrier(Enum):
    premise = 'premise'
    locale = 'locale'


class GraphPolicy(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    default_assumption_carrier: DefaultAssumptionCarrier
    allow_global_axioms: bool
    require_backtranslation_review: bool
    require_dual_formalization_for_core_claims: bool


class ClaimGraph(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: Literal['1.0.0']
    graph_id: Id
    project_id: Id
    created_at: datetime
    updated_at: datetime
    description: Optional[str] = None
    root_claim_ids: Optional[list[Id]] = None
    claims: list[Claim] = Field(..., min_length=1)
    relations: list[Relation]
    graph_policy: Optional[GraphPolicy] = None
