# generated by datamodel-codegen:
#   filename:  pipeline-trace.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal, Optional

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Id(RootModel[str]):
    root: str = Field(..., pattern='^[A-Za-z0-9._:-]+$')


class UnavailableReason(Enum):
    not_applicable = 'not_applicable'
    computation_failed = 'computation_failed'
    runtime_not_captured = 'runtime_not_captured'
    exporter_not_implemented = 'exporter_not_implemented'


class TraceMeta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    trace_id: Id
    schema_version: Literal['1.0.0']
    oae_commit: str
    audit_rules_version: str
    promotion_fsm_version: str
    verifier_versions: dict[str, str]
    source_sha256: str


class SourceUnit(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    unit_id: Id
    start_char: int = Field(..., ge=0)
    end_char: int = Field(..., ge=0)
    text: str


class TraceSource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source_text: str
    source_units: list[SourceUnit]


class StructuringWorkflow(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    planner_action: str
    attempts: list[dict[str, Any]]
    validation_errors: list[str]


class CandidateEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    candidate_id: Id = Field(
        ..., description='Stable candidate identifier (CNT-004/TRC-007)'
    )
    proposal_id: Id = Field(
        ..., description='Stable proposal identifier (CNT-004/TRC-007)'
    )
    source_unit_refs: Optional[list[Id]] = Field(
        None, description='Source units this candidate was extracted from (CNT-004)'
    )
    canonical_text: Optional[str] = Field(
        None, description='Canonical text of the candidate (CNT-004)'
    )
    accepted_as: Optional[Id] = Field(
        None, description='ID of the accepted claim/relation if accepted (CNT-004)'
    )
    merged_into: Optional[Id] = Field(
        None,
        description='ID of the target if merged with existing claim/relation (CNT-004)',
    )
    reject_reason: Optional[str] = Field(
        None, description='Reason for rejection if rejected (CNT-004/TRC-008)'
    )
    is_hard_negative: Optional[bool] = Field(
        False,
        description='Whether this is a hard-negative example for training (CNT-004/TRC-008)',
    )


class CandidateLedger(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    claims_proposed: list[CandidateEntry]
    claims_accepted: list[CandidateEntry]
    claims_rejected: list[CandidateEntry]
    relations_proposed: list[CandidateEntry]
    relations_accepted: list[CandidateEntry]
    relations_rejected: list[CandidateEntry]


class Phase1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    claim_graph: dict[str, Any] = Field(
        ..., description='Reference to a ClaimGraph instance'
    )
    structuring_workflow: StructuringWorkflow
    candidate_ledger: CandidateLedger


class FormalizationAttempt(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    output: str
    sha256: str
    assumptions: list[str]
    back_translation: str


class Divergence(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    classification: str
    primary_target_match: bool
    back_translation_match: bool
    code_sha_match: bool
    assumptions_only_in_a: list[str]
    assumptions_only_in_b: list[str]


class DualFormalization(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attempt_a: FormalizationAttempt
    attempt_b: FormalizationAttempt
    divergence: Divergence


class ClaimAudit(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    trust_frontier: dict[str, Any] = Field(..., description='Trust frontier snapshot')
    model_health: dict[str, Any] = Field(..., description='Model health snapshot')
    intent_alignment: dict[str, Any] = Field(
        ..., description='Intent alignment snapshot'
    )
    blocking_issues: list[str]


class PerClaimRecord(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    dual_formalization: DualFormalization
    build_results: dict[str, Any] = Field(..., description='Build result record')
    verifier_results: dict[str, Any] = Field(..., description='Verifier result record')
    audit: ClaimAudit
    profile: dict[str, Any] = Field(
        ..., description='Reference to an AssuranceProfile instance'
    )
    promotion_transitions: list[dict[str, Any]]


class Phase2Flags(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    phase2_executed: bool
    certification_eligible: bool


class Phase2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    per_claim: dict[str, PerClaimRecord]
    phase2_flags: Phase2Flags


class EvidenceRecord(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    research_output: dict[str, Any] = Field(..., description='Research output record')
    updated_profile: dict[str, Any] = Field(
        ..., description='Reference to an updated AssuranceProfile instance'
    )


class Phase3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    evidence: dict[str, EvidenceRecord]


class SoundnessScore(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    score: float = Field(..., ge=0.0, le=1.0)
    method: str
    notes: list[str]


class TraceResults(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    forward_traces: dict[str, Any] = Field(
        ..., description='Forward trace records keyed by claim_id'
    )
    forward_traces_unavailable_reason: Optional[UnavailableReason] = Field(
        None, description='Required when forward_traces is empty (CNT-007)'
    )
    backward_traces: dict[str, Any] = Field(
        ..., description='Backward trace records keyed by claim_id'
    )
    backward_traces_unavailable_reason: Optional[UnavailableReason] = Field(
        None, description='Required when backward_traces is empty (CNT-007)'
    )
    gap_analysis: dict[str, Any] = Field(..., description='Gap analysis results')
    soundness: SoundnessScore
    propagation_traces: Optional[list[dict[str, Any]]] = Field(
        None, description='Propagation trace records (TRC-010)'
    )
    vector_score_deltas: Optional[list[dict[str, Any]]] = Field(
        None, description='Vector score delta records (TRC-010)'
    )


class PipelineTraceV1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: Literal['1.0.0']
    meta: TraceMeta
    source: TraceSource
    phase1: Phase1
    phase2: Phase2
    phase3: Phase3
    trace_results: TraceResults
