# generated by datamodel-codegen:
#   filename:  pipeline-trace-v2.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal, Optional

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Id(RootModel[str]):
    root: str = Field(
        ...,
        description='Stable identifier. Must be non-empty and safe for use as map keys.',
        pattern='^[A-Za-z0-9._:-]+$',
    )


class UnavailableReason(Enum):
    not_applicable = 'not_applicable'
    computation_failed = 'computation_failed'
    runtime_not_captured = 'runtime_not_captured'
    exporter_not_implemented = 'exporter_not_implemented'


class TraceMeta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    trace_id: Id = Field(..., description='Globally unique trace identifier.')
    schema_version: Literal['2.0.0']
    oae_commit: str = Field(
        ..., description='Git commit SHA of the OAE engine that produced this trace.'
    )
    audit_rules_version: str = Field(
        ..., description='Version of the audit-rules package used.'
    )
    promotion_fsm_version: str = Field(
        ..., description='Version of the promotion state machine definition used.'
    )
    verifier_versions: dict[str, str] = Field(
        ...,
        description='Map of verifier name to version string for every verifier invoked.',
    )
    source_sha256: str = Field(..., description='SHA-256 hash of the raw source_text.')


class SourceUnit(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    unit_id: Id = Field(
        ..., description='Stable unit identifier for source-unit grounding.'
    )
    start_char: int = Field(
        ..., description='Inclusive start character offset within source_text.', ge=0
    )
    end_char: int = Field(
        ..., description='Exclusive end character offset within source_text.', ge=0
    )
    text: str = Field(..., description='The source unit text span.')


class TraceSource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source_text: str = Field(..., description='Full source document text.')
    source_units: list[SourceUnit] = Field(
        ...,
        description='Segmented source units with character offsets into source_text.',
    )


class ClaimNode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    node_id: Id
    type: str = Field(
        ..., description='Node type: claim, evidence, hidden_assumption, etc.'
    )
    text: str
    canonical_text: Optional[str] = None
    status: Optional[str] = None
    lifecycle: Optional[str] = None
    confidence: Optional[float] = None
    source_unit_refs: Optional[list[Id]] = Field(
        None, description='References to source units this node was extracted from.'
    )
    tags: Optional[list[str]] = Field(
        None,
        description='Descriptive tags. Must NOT contain domain-leak values (tracer_domain, scope.domain, etc.).',
    )


class ClaimEdge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    edge_id: Id
    src: Id
    tgt: Id
    relation_type: str
    strength: Optional[str] = None
    weight: Optional[float] = None


class ClaimGraph(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    claims: list[ClaimNode] = Field(
        ..., description='All claim/evidence/hidden-assumption nodes.'
    )
    relations: list[ClaimEdge] = Field(
        ..., description='All typed edges between nodes.'
    )


class StructuringWorkflow(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    planner_action: Optional[str] = Field(
        ..., description='The planner action that initiated structuring.'
    )
    attempts: list[dict[str, Any]] = Field(
        ..., description='Structuring attempt records.'
    )
    validation_errors: list[str] = Field(
        ..., description='Validation errors encountered during structuring.'
    )


class ClaimCandidateEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    candidate_id: Id = Field(..., description='Stable candidate identifier.')
    proposal_id: Id = Field(..., description='Stable proposal lineage identifier.')
    canonical_text: str = Field(..., description='Canonicalized claim text.')
    raw_text: str = Field(
        ..., description='Original claim text before canonicalization.'
    )
    type: str = Field(
        ..., description='Dataset-facing semantic type for this claim candidate.'
    )
    source_unit_refs: list[Id] = Field(
        ..., description='Source units this candidate was extracted from.'
    )
    accepted: bool = Field(
        ...,
        description='Whether the candidate was admitted into the final phase1 graph.',
    )
    accepted_as: Optional[Id] = Field(
        None, description='ID of the accepted claim if accepted, null otherwise.'
    )
    merged_into: Optional[Id] = Field(
        None, description='ID of the target claim if merged, null otherwise.'
    )
    reject_reason: Optional[str] = Field(
        None, description='Reason for rejection if rejected, null otherwise.'
    )


class RelationCandidateEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    candidate_id: Id = Field(..., description='Stable candidate identifier.')
    proposal_id: Id = Field(..., description='Stable proposal lineage identifier.')
    src_id: Id = Field(..., description='Source claim ID.')
    tgt_id: Id = Field(..., description='Target claim ID.')
    relation_type: str = Field(
        ..., description='Semantic relation label emitted for the dataset.'
    )
    strength: Optional[str] = Field(
        ..., description='Relation strength, null when unavailable.'
    )
    accepted: bool = Field(
        ...,
        description='Whether the relation proposal was admitted into the final phase1 graph.',
    )
    accepted_as: Optional[Id] = Field(
        None, description='ID of the accepted relation if accepted, null otherwise.'
    )
    reject_reason: Optional[str] = Field(
        None, description='Reason for rejection if rejected, null otherwise.'
    )


class CandidateLedger(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    claims_proposed: list[ClaimCandidateEntry] = Field(
        ..., description='All proposed claim candidates.'
    )
    claims_accepted: list[ClaimCandidateEntry] = Field(
        ..., description='Accepted claim candidates.'
    )
    claims_rejected: list[ClaimCandidateEntry] = Field(
        ..., description='Rejected claim candidates.'
    )
    relations_proposed: list[RelationCandidateEntry] = Field(
        ..., description='All proposed relation candidates.'
    )
    relations_accepted: list[RelationCandidateEntry] = Field(
        ..., description='Accepted relation candidates.'
    )
    relations_rejected: list[RelationCandidateEntry] = Field(
        ..., description='Rejected relation candidates.'
    )


class Phase1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    claim_graph: ClaimGraph = Field(
        ..., description='Structured claim graph produced by phase 1.'
    )
    structuring_workflow: StructuringWorkflow
    candidate_ledger: CandidateLedger


class FormalizationAttempt(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    output: str = Field(..., description='Formalization output text.')
    sha256: str = Field(
        ..., description='SHA-256 of the output for deterministic comparison.'
    )
    assumptions: list[str] = Field(
        ..., description='Assumptions discovered during formalization.'
    )
    back_translation: Optional[str] = Field(
        None, description='Natural language back-translation of the formal output.'
    )


class Classification(Enum):
    match = 'match'
    minor = 'minor'
    major = 'major'
    critical = 'critical'


class Divergence(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    classification: Classification = Field(
        ..., description='Divergence severity classification.'
    )
    primary_target_match: bool
    back_translation_match: bool
    code_sha_match: bool
    assumptions_only_in_a: list[str]
    assumptions_only_in_b: list[str]


class DualFormalization(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    attempt_a: FormalizationAttempt
    attempt_b: FormalizationAttempt
    divergence: Divergence


class ClaimAudit(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    trust_frontier: dict[str, Any] = Field(..., description='Trust frontier snapshot.')
    model_health: dict[str, Any] = Field(..., description='Model health snapshot.')
    intent_alignment: dict[str, Any] = Field(
        ..., description='Intent alignment snapshot.'
    )
    blocking_issues: list[str] = Field(
        ..., description='List of blocking issues preventing promotion.'
    )


class PromotionTransition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    transition_id: Id = Field(..., description='Stable transition identifier.')
    gate_before: str = Field(..., description='Gate value before transition.')
    gate_after: str = Field(..., description='Gate value after transition.')
    actor_role: str = Field(
        ..., description='Role of the actor who initiated the transition.'
    )
    allowed: bool = Field(
        ..., description='Whether the state machine permitted this transition.'
    )
    override: bool = Field(..., description='Whether an override rule was applied.')
    rationale: Optional[str] = Field(
        None, description='Textual rationale for the transition.'
    )
    timestamp: str = Field(..., description='ISO 8601 timestamp of the transition.')


class PerClaimRecord(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    dual_formalization: Optional[DualFormalization] = Field(
        ..., description='Dual formalization record, null if not performed.'
    )
    build_results: dict[str, Any] = Field(..., description='Build result record.')
    verifier_results: dict[str, Any] = Field(..., description='Verifier result record.')
    audit: Optional[ClaimAudit] = Field(
        ..., description='Audit record, null if audit not performed.'
    )
    profile: Optional[dict[str, Any]] = Field(
        ..., description='AssuranceProfile snapshot, null if not yet computed.'
    )
    promotion_transitions: list[PromotionTransition] = Field(
        ..., description='Ordered list of promotion state machine transitions.'
    )


class Phase2Flags(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    phase2_executed: bool = Field(..., description='Whether phase 2 was executed.')
    formalization_required: Optional[bool] = Field(
        None, description='Whether formalization was required for this run.'
    )
    certification_eligible: bool = Field(
        ..., description='Whether the run is eligible for certification.'
    )
    unavailable_reason: Optional[UnavailableReason] = Field(
        None, description='Why phase 2 was not executed, if applicable.'
    )


class Phase2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    per_claim: dict[str, PerClaimRecord] = Field(
        ..., description='Map of claim_id to per-claim phase 2 record.'
    )
    phase2_flags: Phase2Flags


class EvidenceRecord(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    research_output: dict[str, Any] = Field(..., description='Research output record.')
    updated_profile: Optional[dict[str, Any]] = Field(
        None,
        description='Updated AssuranceProfile after evidence integration, null if not recomputed.',
    )


class Phase3Flags(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    phase3_executed: bool = Field(..., description='Whether phase 3 was executed.')
    unavailable_reason: Optional[UnavailableReason] = Field(
        None, description='Why phase 3 was not executed, if applicable.'
    )


class Phase3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    evidence: dict[str, EvidenceRecord] = Field(
        ..., description='Map of claim_id to evidence record.'
    )
    phase3_flags: Optional[Phase3Flags] = Field(
        None, description='Phase 3 execution flags.'
    )


class PropagationPathEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    claim_id: Id
    status_before: str
    status_after: str
    reason: str = Field(
        ..., description='Which edge or rule caused this propagation step.'
    )


class PropagationTrace(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    trigger_claim_id: Id = Field(
        ..., description='The node whose status change triggered propagation.'
    )
    trigger_event_id: Optional[Id] = Field(
        None, description='The originating event, if available.'
    )
    path: list[PropagationPathEntry] = Field(
        ..., description='Ordered propagation path.'
    )


class VectorScores(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    trust_base_integrity: float
    intent_alignment: float
    evidence_support: float
    coverage: float
    robustness: float


class VectorScoreDelta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    claim_id: Id
    event_id: Optional[Id] = Field(
        None, description='The originating event, if available.'
    )
    before: VectorScores
    after: VectorScores
    gate_before: Optional[str] = None
    gate_after: Optional[str] = None


class SoundnessScore(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    score: float = Field(..., ge=0.0, le=1.0)
    method: str
    notes: list[str]


class TraceResults(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    forward_traces: dict[str, Any] = Field(
        ..., description='Forward trace records keyed by claim_id.'
    )
    forward_traces_unavailable_reason: Optional[UnavailableReason] = Field(
        None, description='Required when forward_traces is empty.'
    )
    backward_traces: dict[str, Any] = Field(
        ..., description='Backward trace records keyed by claim_id.'
    )
    backward_traces_unavailable_reason: Optional[UnavailableReason] = Field(
        None, description='Required when backward_traces is empty.'
    )
    gap_analysis: dict[str, Any] = Field(..., description='Gap analysis results.')
    gap_analysis_unavailable_reason: Optional[UnavailableReason] = Field(
        None, description='Required when gap_analysis is empty.'
    )
    soundness: SoundnessScore
    propagation_traces: Optional[list[PropagationTrace]] = Field(
        None,
        description='Propagation trace records showing how status changes cascade.',
    )
    propagation_traces_unavailable_reason: Optional[UnavailableReason] = Field(
        None, description='Required when propagation_traces is empty.'
    )
    vector_score_deltas: Optional[list[VectorScoreDelta]] = Field(
        None, description='Vector score delta records tracking score changes over time.'
    )
    vector_score_deltas_unavailable_reason: Optional[UnavailableReason] = Field(
        None, description='Required when vector_score_deltas is empty.'
    )


class PipelineTraceV2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: Literal['2.0.0']
    meta: TraceMeta
    source: TraceSource
    phase1: Phase1
    phase2: Phase2
    phase3: Phase3
    trace_results: TraceResults
