# generated by datamodel-codegen:
#   filename:  pipeline-event.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal, Optional

from pydantic import BaseModel, ConfigDict, Field, RootModel, model_validator


class Phase(Enum):
    phase1 = 'phase1'
    phase2 = 'phase2'
    phase3 = 'phase3'
    trace = 'trace'


class EventType(Enum):
    propose_relation = 'propose_relation'
    add_hidden_assumption = 'add_hidden_assumption'
    request_recheck = 'request_recheck'
    select_formalization = 'select_formalization'
    finalize_profile = 'finalize_profile'
    propose_promotion = 'propose_promotion'


class Actor(Enum):
    planner = 'planner'
    formalizer = 'formalizer'
    auditor = 'auditor'
    system = 'system'
    human = 'human'


class Id(RootModel[str]):
    root: str = Field(..., pattern='^[A-Za-z0-9._:-]+$')


class EventClass(Enum):
    controllable_action = 'controllable_action'
    automatic_consequence = 'automatic_consequence'


class UnavailableReason(Enum):
    not_applicable = 'not_applicable'
    computation_failed = 'computation_failed'
    runtime_not_captured = 'runtime_not_captured'
    exporter_not_implemented = 'exporter_not_implemented'


class OmissionReason(Enum):
    not_requested = 'not_requested'
    unsupported = 'unsupported'
    cost_policy = 'cost_policy'
    runtime_limit = 'runtime_limit'


class VerifierDelta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    legality: Optional[bool] = None
    vector_score_delta: Optional[dict[str, Any]] = None
    vector_score_delta_unavailable_reason: Optional[UnavailableReason] = Field(
        None, description='Required when vector_score_delta is null (CNT-007)'
    )
    gate_before: Optional[str] = None
    gate_after: Optional[str] = None
    contradiction_delta: Optional[dict[str, Any]] = None
    hidden_assumptions_added: Optional[list[str]] = None
    profile_recomputed: Optional[bool] = None


class PipelineEventV1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: Literal['1.0.0']
    event_id: Id = Field(
        ..., description='Stable unique identifier for this event (CNT-006)'
    )
    trace_id: Id
    step_id: Id
    cause_event_id: Optional[Id] = Field(
        None,
        description='Event that caused this automatic consequence (CNT-006). Null for controllable actions.',
    )
    phase: Phase
    event_type: EventType
    event_class: EventClass = Field(
        ...,
        description='Controllable action vs automatic consequence (CNT-006/TRC-009)',
    )
    actor: Actor
    before_hash: str
    after_hash: str
    proposal: Optional[dict[str, Any]] = None
    accepted: Optional[bool] = None
    reject_reason: Optional[str] = None
    changed_ids: list[Id]
    verifier_delta: VerifierDelta

    @model_validator(mode='after')
    def _validate_conditional_fields(self) -> 'PipelineEventV1':
        if self.accepted is False and not self.reject_reason:
            raise ValueError('reject_reason is required when accepted is false')
        return self
