# generated by datamodel-codegen:
#   filename:  pipeline-event-v2.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal, Optional

from pydantic import BaseModel, ConfigDict, Field, RootModel, model_validator


class Phase(Enum):
    phase1 = 'phase1'
    phase2 = 'phase2'
    phase3 = 'phase3'
    trace = 'trace'


class EventType(Enum):
    propose_relation = 'propose_relation'
    add_hidden_assumption = 'add_hidden_assumption'
    request_recheck = 'request_recheck'
    select_formalization = 'select_formalization'
    finalize_profile = 'finalize_profile'
    propose_promotion = 'propose_promotion'
    profile_recomputed = 'profile_recomputed'
    propagation_applied = 'propagation_applied'
    gate_updated = 'gate_updated'
    audit_completed = 'audit_completed'


class Actor(Enum):
    planner = 'planner'
    formalizer = 'formalizer'
    auditor = 'auditor'
    system = 'system'
    human = 'human'


class Id(RootModel[str]):
    root: str = Field(
        ...,
        description='Stable identifier. Must be non-empty and safe for use as map keys.',
        pattern='^[A-Za-z0-9._:-]+$',
    )


class EventClass(Enum):
    controllable_action = 'controllable_action'
    automatic_consequence = 'automatic_consequence'


class UnavailableReason(Enum):
    not_applicable = 'not_applicable'
    computation_failed = 'computation_failed'
    runtime_not_captured = 'runtime_not_captured'
    exporter_not_implemented = 'exporter_not_implemented'


class VerifierDelta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    legality: Optional[bool] = Field(
        None, description='Whether the action was legal per state machine rules.'
    )
    vector_score_delta: Optional[dict[str, Any]] = Field(
        None, description='Structured vector score changes.'
    )
    vector_score_delta_unavailable_reason: Optional[UnavailableReason] = Field(
        None, description='Required when vector_score_delta is null.'
    )
    gate_before: Optional[str] = Field(
        None, description='Gate value before this event.'
    )
    gate_after: Optional[str] = Field(None, description='Gate value after this event.')
    contradiction_delta: Optional[dict[str, Any]] = Field(
        None, description='Changes to contradiction state.'
    )
    hidden_assumptions_added: Optional[list[str]] = Field(
        None, description='Hidden assumptions surfaced by this event.'
    )
    profile_recomputed: Optional[bool] = Field(
        None, description='Whether the assurance profile was recomputed.'
    )
    unavailable_reason: Optional[UnavailableReason] = Field(
        None, description='Why the verifier delta is partially or fully unavailable.'
    )


class PipelineEventV2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: Literal['2.0.0']
    event_id: Id = Field(..., description='Stable unique identifier for this event.')
    trace_id: Id = Field(..., description='Trace this event belongs to.')
    step_id: Id = Field(..., description='Step within the trace.')
    event_seq: int = Field(
        ...,
        description='Monotonically increasing sequence number within the trace.',
        ge=0,
    )
    phase: Phase = Field(..., description='Pipeline phase this event occurred in.')
    event_type: EventType = Field(
        ...,
        description='Canonical event type. Controllable actions: propose_relation, add_hidden_assumption, request_recheck, select_formalization, finalize_profile, propose_promotion. Automatic consequences: profile_recomputed, propagation_applied, gate_updated, audit_completed.',
    )
    event_class: EventClass = Field(
        ...,
        description='Whether this event is a controllable agent/user action or an automatic system consequence.',
    )
    actor: Actor = Field(
        ..., description='The actor role that initiated or owns this event.'
    )
    cause_event_id: Optional[Id] = Field(
        None,
        description='For automatic_consequence events: the event_id of the controllable action that caused this consequence. Null for controllable_action events.',
    )
    before_hash: str = Field(
        ..., description='Hash of the relevant state before this event.'
    )
    after_hash: str = Field(
        ..., description='Hash of the relevant state after this event.'
    )
    changed_ids: list[Id] = Field(
        ...,
        description='IDs of claims, relations, or other entities modified by this event.',
    )
    proposal: Optional[dict[str, Any]] = Field(
        None,
        description='Structured proposal payload, if this event proposes a change.',
    )
    accepted: Optional[bool] = Field(
        None,
        description='Whether the proposal was accepted. Null if no proposal was made.',
    )
    reject_reason: Optional[str] = Field(
        None, description='Required when accepted=false. Reason for rejection.'
    )
    verifier_delta: Optional[VerifierDelta] = Field(
        None, description='Structured verifier state changes caused by this event.'
    )

    @model_validator(mode='after')
    def _validate_conditional_fields(self) -> 'PipelineEventV2':
        if self.event_class == EventClass.automatic_consequence and self.cause_event_id is None:
            raise ValueError('cause_event_id is required for automatic_consequence events')
        if self.accepted is False and not self.reject_reason:
            raise ValueError('reject_reason is required when accepted is false')
        return self
