# generated by datamodel-codegen:
#   filename:  prefix-slice.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal, Optional

from pydantic import BaseModel, ConfigDict, Field, RootModel, model_validator


class Id(RootModel[str]):
    root: str = Field(..., pattern='^[A-Za-z0-9._:-]+$')


class OmissionReason(Enum):
    not_requested = 'not_requested'
    unsupported = 'unsupported'
    cost_policy = 'cost_policy'
    runtime_limit = 'runtime_limit'


class PrefixSliceTextV1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: Literal['1.0.0']
    trace_id: Id
    step_id: Id
    state_text: str = Field(
        ...,
        description='Domain-free canonical serialization of the current pipeline state',
    )
    available_artifacts: list[str]
    legal_action_mask: Optional[list[str]] = None
    gold_action: Optional[dict[str, Any]] = Field(
        None, description='Gold-standard action for SFT training only'
    )
    omission_reason: Optional[OmissionReason] = Field(
        None, description='Why a canonical field was intentionally omitted (CNT-007)'
    )

    @model_validator(mode='after')
    def _validate_model_visible_fields(self) -> 'PrefixSliceTextV1':
        trace_id = self.trace_id.root if hasattr(self.trace_id, 'root') else str(self.trace_id)
        if str(trace_id).strip().lower() in {'placeholder', 'tbd', 'todo'}:
            raise ValueError('trace_id must not be a placeholder')
        if 'source_domain' in self.state_text:
            raise ValueError('state_text must not contain source_domain')
        return self


PrefixSliceV1 = PrefixSliceTextV1
