# generated by datamodel-codegen:
#   filename:  prefix-slice-graph.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal, Optional

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Id(RootModel[str]):
    root: str = Field(..., pattern='^[A-Za-z0-9._:-]+$')


class OmissionReason(Enum):
    not_requested = 'not_requested'
    unsupported = 'unsupported'
    cost_policy = 'cost_policy'
    runtime_limit = 'runtime_limit'


class GraphNode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    node_id: Id
    role: str = Field(..., description='Node role (e.g. claim, assumption)')
    status: str = Field(..., description='Current status at prefix cutoff')
    gate: Optional[str] = None
    profile_summary: Optional[dict[str, Any]] = None


class GraphEdge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Id
    target: Id
    relation_type: str
    strength: Optional[float] = None
    is_hidden_assumption: Optional[bool] = False


class StateGraphV1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    nodes: list[GraphNode] = Field(
        ..., description='Graph nodes representing claims/relations at prefix cutoff'
    )
    edges: list[GraphEdge] = Field(
        ..., description='Graph edges representing relations at prefix cutoff'
    )


class PrefixSliceGraphV1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: Literal['1.0.0']
    trace_id: Id
    step_id: Id
    state_graph: StateGraphV1 = Field(
        ...,
        description='Graph-native projection of the current pipeline state at prefix cutoff',
    )
    available_artifacts: list[str]
    legal_action_mask: Optional[list[str]] = None
    gold_action: Optional[dict[str, Any]] = Field(
        None, description='Gold-standard action for SFT training only'
    )
    omission_reason: Optional[OmissionReason] = Field(
        None, description='Why a canonical field was intentionally omitted (CNT-007)'
    )
