# generated by datamodel-codegen:
#   filename:  prefix-slice-text-v1.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel, model_validator


class Id(RootModel[str]):
    root: str = Field(..., pattern='^[A-Za-z0-9._:-]+$')


class ActionDsl(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action: str = Field(..., description='Canonical ActionDSL verb.')
    action_type: Optional[str] = Field(
        None, description='Temporary compatibility mirror of action.'
    )
    dsl: Optional[str] = Field(
        None, description='Compatibility DSL string for rollout/debugging.'
    )
    arguments: dict[str, Any] = Field(
        ..., description='Canonical ActionDSL arguments keyed by frozen argument names.'
    )


class OmissionReason(Enum):
    not_requested = 'not_requested'
    unsupported = 'unsupported'
    cost_policy = 'cost_policy'
    runtime_limit = 'runtime_limit'


class PrefixSliceTextV1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: Literal['1.0.0']
    trace_id: Id = Field(
        ..., description='Stable trace identifier. Must not be empty or a placeholder.'
    )
    step_id: Id = Field(
        ..., description='Step within the trace at the prefix cutoff point.'
    )
    state_text: str = Field(
        ...,
        description='Domain-free canonical serialization of the current pipeline state at prefix cutoff. Must be non-empty. No domain, router, prompt-template, or corpus metadata.',
        min_length=1,
    )
    available_artifacts: list[str] = Field(
        ..., description='List of artifact identifiers available at this prefix cutoff.'
    )
    legal_action_mask: Optional[list[Union[str, ActionDsl]]] = Field(
        None, description='Subset of actions that are legal at this prefix cutoff.'
    )
    gold_action: Optional[ActionDsl] = Field(
        None,
        description='Gold-standard action for SFT training. ActionDSL object or null.',
    )
    omission_reason: Optional[OmissionReason] = Field(
        None,
        description='Why a canonical field was intentionally omitted from this derived projection.',
    )

    @model_validator(mode='after')
    def _validate_model_visible_fields(self) -> 'PrefixSliceTextV1':
        trace_id = self.trace_id.root if hasattr(self.trace_id, 'root') else str(self.trace_id)
        if str(trace_id).strip().lower() in {'placeholder', 'tbd', 'todo'}:
            raise ValueError('trace_id must not be a placeholder')
        if 'source_domain' in self.state_text:
            raise ValueError('state_text must not contain source_domain')
        return self
