# generated by datamodel-codegen:
#   filename:  prefix-slice-graph-v1.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel, model_validator


class Id(RootModel[str]):
    root: str = Field(..., pattern='^[A-Za-z0-9._:-]+$')


class ActionDsl(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action: str = Field(..., description='Canonical ActionDSL verb.')
    action_type: Optional[str] = Field(
        None, description='Temporary compatibility mirror of action.'
    )
    dsl: Optional[str] = Field(
        None, description='Compatibility DSL string for rollout/debugging.'
    )
    arguments: dict[str, Any] = Field(
        ..., description='Canonical ActionDSL arguments keyed by frozen argument names.'
    )


class OmissionReason(Enum):
    not_requested = 'not_requested'
    unsupported = 'unsupported'
    cost_policy = 'cost_policy'
    runtime_limit = 'runtime_limit'


class GraphNode(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    node_id: Id = Field(..., description='Stable node identifier.')
    role: str = Field(..., description='Node role (e.g. claim, assumption).')
    status: str = Field(..., description='Current status at prefix cutoff.')
    gate: Optional[str] = Field(None, description='Assurance gate at prefix cutoff.')
    profile_summary: Optional[dict[str, Any]] = Field(
        None,
        description='Summary of the assurance profile at prefix cutoff. Must not contain future snapshots.',
    )


class GraphEdge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: Id = Field(..., description='Source node identifier.')
    target: Id = Field(..., description='Target node identifier.')
    relation_type: str = Field(
        ..., description='Type of the relation (e.g. dependsOn, contradicts).'
    )
    strength: Optional[str] = Field(None, description='Relation strength label.')
    is_hidden_assumption: Optional[bool] = Field(
        False,
        description='Whether this edge was surfaced by hidden assumption discovery.',
    )


class StateGraphV1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    nodes: list[GraphNode] = Field(
        ..., description='Graph nodes representing claims/relations at prefix cutoff.'
    )
    edges: list[GraphEdge] = Field(
        ..., description='Graph edges representing relations at prefix cutoff.'
    )


class PrefixSliceGraphV1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: Literal['1.0.0']
    trace_id: Id = Field(
        ..., description='Stable trace identifier. Must not be empty or a placeholder.'
    )
    step_id: Id = Field(
        ..., description='Step within the trace at the prefix cutoff point.'
    )
    state_graph: StateGraphV1 = Field(
        ...,
        description='Graph-native projection of the current pipeline state at prefix cutoff. No future profile, evidence, promotion, or soundness leakage.',
    )
    available_artifacts: list[str] = Field(
        ..., description='List of artifact identifiers available at this prefix cutoff.'
    )
    legal_action_mask: Optional[list[Union[str, ActionDsl]]] = Field(
        None, description='Subset of actions that are legal at this prefix cutoff.'
    )
    gold_action: Optional[ActionDsl] = Field(
        None,
        description='Gold-standard action for SFT training. ActionDSL object or null.',
    )
    omission_reason: Optional[OmissionReason] = Field(
        None,
        description='Why a canonical field was intentionally omitted from this derived projection.',
    )

    @model_validator(mode='after')
    def _validate_trace_id(self) -> 'PrefixSliceGraphV1':
        trace_id = self.trace_id.root if hasattr(self.trace_id, 'root') else str(self.trace_id)
        if str(trace_id).strip().lower() in {'placeholder', 'tbd', 'todo'}:
            raise ValueError('trace_id must not be a placeholder')
        return self
