# generated by datamodel-codegen:
#   filename:  trace-sidecar-meta-v2.schema.json

from __future__ import annotations

from typing import Any, Literal, Optional

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Id(RootModel[str]):
    root: str = Field(..., pattern='^[A-Za-z0-9._:-]+$')


class TraceSidecarMetaV2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: Literal['2.0.0']
    trace_id: Id = Field(
        ..., description='Stable trace identifier matching the associated trace.json.'
    )
    source_domain: str = Field(
        ...,
        description='Domain tag for sampling/analysis. Never exposed to model-visible artifacts.',
    )
    source_uri: Optional[str] = Field(
        None, description='URI of the source document or corpus entry.'
    )
    corpus_name: Optional[str] = Field(
        None, description='Name of the corpus this trace was sampled from.'
    )
    license: Optional[str] = Field(
        None, description='License governing the source material.'
    )
    split: Optional[str] = Field(
        None, description='Dataset split (train/val/test) for sampling control.'
    )
    notes: Optional[dict[str, Any]] = Field(
        None,
        description='Freeform operator notes. Never exposed to model-visible artifacts.',
    )
