# generated by datamodel-codegen:
#   filename:  trace-sidecar-meta.schema.json

from __future__ import annotations

from typing import Any, Literal, Optional

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Id(RootModel[str]):
    root: str = Field(..., pattern='^[A-Za-z0-9._:-]+$')


class TraceSidecarMeta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: Literal['1.0.0']
    trace_id: Id
    source_domain: str
    source_uri: Optional[str] = None
    corpus_name: Optional[str] = None
    license: Optional[str] = None
    split: Optional[str] = None
    notes: Optional[dict[str, Any]] = None
